// frontend/bin/commercial/components/organisms/Navigation/Navigation.tsx
'use client'

import Link from 'next/link'
import { Button } from '@/components/atoms/Button/Button'
import { Menu, X, Github } from 'lucide-react'
import { useState } from 'react'
import { ThemeToggle } from '@/components/molecules/ThemeToggle/ThemeToggle'
import { NavLink } from '@/components/molecules'

export function Navigation() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)

  return (
    <nav className="fixed top-0 left-0 right-0 z-50 bg-background/95 backdrop-blur-sm border-b border-border">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          {/* Logo */}
          <Link
            href="/"
            className="flex items-center gap-2 text-xl font-semibold text-primary hover:text-primary/80 transition-colors"
          >
            <span className="text-2xl">🐝</span>
            <span>rbee</span>
          </Link>

          {/* Desktop Navigation */}
          <div className="hidden md:flex items-center gap-8">
            <NavLink href="/features">Features</NavLink>
            <NavLink href="/use-cases">Use Cases</NavLink>
            <NavLink href="/pricing">Pricing</NavLink>
            <NavLink href="/developers">For Developers</NavLink>
            <NavLink href="/gpu-providers">For Providers</NavLink>
            <NavLink href="/enterprise">For Enterprise</NavLink>
            <NavLink href="https://github.com/veighnsche/llama-orch/tree/main/docs">Docs</NavLink>

            <div className="flex items-center gap-2">
              <a
                href="https://github.com/veighnsche/llama-orch"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center justify-center size-9 rounded-md text-muted-foreground hover:text-foreground transition-colors cursor-pointer"
                aria-label="GitHub"
              >
                <Github className="w-5 h-5" />
              </a>

              <ThemeToggle />
            </div>

            <Button size="sm" className="bg-primary hover:bg-primary/80 text-primary-foreground">
              Join Waitlist
            </Button>
          </div>

          {/* Mobile Menu Button & Theme Toggle */}
          <div className="md:hidden flex items-center gap-2">
            <ThemeToggle />
            <button
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
              className="text-muted-foreground hover:text-foreground"
            >
              {mobileMenuOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
            </button>
          </div>
        </div>

        {/* Mobile Menu */}
        {mobileMenuOpen && (
          <div className="md:hidden py-4 space-y-4 border-t border-border">
            <NavLink href="/features" variant="mobile" onClick={() => setMobileMenuOpen(false)}>
              Features
            </NavLink>
            <NavLink href="/use-cases" variant="mobile" onClick={() => setMobileMenuOpen(false)}>
              Use Cases
            </NavLink>
            <NavLink href="/pricing" variant="mobile" onClick={() => setMobileMenuOpen(false)}>
              Pricing
            </NavLink>
            <NavLink href="/developers" variant="mobile" onClick={() => setMobileMenuOpen(false)}>
              For Developers
            </NavLink>
            <NavLink href="/gpu-providers" variant="mobile" onClick={() => setMobileMenuOpen(false)}>
              For Providers
            </NavLink>
            <NavLink href="/enterprise" variant="mobile" onClick={() => setMobileMenuOpen(false)}>
              For Enterprise
            </NavLink>
            <NavLink
              href="https://github.com/veighnsche/llama-orch/tree/main/docs"
              variant="mobile"
              onClick={() => setMobileMenuOpen(false)}
            >
              Docs
            </NavLink>
            <a
              href="https://github.com/veighnsche/llama-orch"
              target="_blank"
              rel="noopener noreferrer"
              className="block text-muted-foreground hover:text-foreground transition-colors"
            >
              GitHub
            </a>
            <Button size="sm" className="w-full bg-primary hover:bg-primary/80 text-primary-foreground">
              Join Waitlist
            </Button>
          </div>
        )}
      </div>
    </nav>
  )
}

// frontend/bin/commercial/app/stories/organisms/Navigation/Navigation.vue
<!-- Created by: TEAM-FE-000 (Scaffolding) -->
<!-- TEAM-FE-CONSOLIDATE: Ported from reference/v0 navigation component with design tokens -->
<!-- TEAM-FE-010: Added ThemeToggle button from shared storybook -->
<script setup lang="ts">
import { ref } from 'vue'
import { Button, ThemeToggle } from '~/stories'
import { Menu, X, Github } from 'lucide-vue-next'

const mobileMenuOpen = ref(false)

const toggleMobileMenu = () => {
  mobileMenuOpen.value = !mobileMenuOpen.value
}

const closeMobileMenu = () => {
  mobileMenuOpen.value = false
}
</script>

<template>
  <nav class="fixed top-0 left-0 right-0 z-50 bg-background/95 backdrop-blur-sm border-b border-border">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between h-16">
        <!-- Logo -->
        <NuxtLink
          to="/"
          class="flex items-center gap-2 text-xl font-semibold text-primary hover:text-primary/80 transition-colors"
        >
          <span class="text-2xl">🐝</span>
          <span>rbee</span>
        </NuxtLink>

        <!-- Desktop Navigation -->
        <div class="hidden md:flex items-center gap-8">
          <NuxtLink to="/features" class="text-muted-foreground hover:text-foreground transition-colors">
            Features
          </NuxtLink>
          <NuxtLink to="/use-cases" class="text-muted-foreground hover:text-foreground transition-colors">
            Use Cases
          </NuxtLink>
          <NuxtLink to="/pricing" class="text-muted-foreground hover:text-foreground transition-colors">
            Pricing
          </NuxtLink>
          <NuxtLink to="/developers" class="text-muted-foreground hover:text-foreground transition-colors">
            For Developers
          </NuxtLink>
          <NuxtLink to="/providers" class="text-muted-foreground hover:text-foreground transition-colors">
            For Providers
          </NuxtLink>
          <NuxtLink to="/enterprise" class="text-muted-foreground hover:text-foreground transition-colors">
            For Enterprise
          </NuxtLink>

          <a
            href="https://github.com/veighnsche/llama-orch"
            target="_blank"
            rel="noopener noreferrer"
            class="text-muted-foreground hover:text-foreground transition-colors"
          >
            <Github :size="20" />
          </a>

          <ThemeToggle />

          <Button size="sm" variant="default">
            Join Waitlist
          </Button>
        </div>

        <!-- Mobile Menu Button -->
        <button
          @click="toggleMobileMenu"
          class="md:hidden text-muted-foreground hover:text-foreground"
        >
          <X v-if="mobileMenuOpen" :size="24" />
          <Menu v-else :size="24" />
        </button>
      </div>

      <!-- Mobile Menu -->
      <div v-if="mobileMenuOpen" class="md:hidden py-4 space-y-4 border-t border-border">
        <NuxtLink
          to="/features"
          class="block text-muted-foreground hover:text-foreground transition-colors"
          @click="closeMobileMenu"
        >
          Features
        </NuxtLink>
        <NuxtLink
          to="/use-cases"
          class="block text-muted-foreground hover:text-foreground transition-colors"
          @click="closeMobileMenu"
        >
          Use Cases
        </NuxtLink>
        <NuxtLink
          to="/pricing"
          class="block text-muted-foreground hover:text-foreground transition-colors"
          @click="closeMobileMenu"
        >
          Pricing
        </NuxtLink>
        <NuxtLink
          to="/developers"
          class="block text-muted-foreground hover:text-foreground transition-colors"
          @click="closeMobileMenu"
        >
          For Developers
        </NuxtLink>
        <NuxtLink
          to="/providers"
          class="block text-muted-foreground hover:text-foreground transition-colors"
          @click="closeMobileMenu"
        >
          For Providers
        </NuxtLink>
        <NuxtLink
          to="/enterprise"
          class="block text-muted-foreground hover:text-foreground transition-colors"
          @click="closeMobileMenu"
        >
          For Enterprise
        </NuxtLink>
        <a
          href="https://github.com/veighnsche/llama-orch"
          target="_blank"
          rel="noopener noreferrer"
          class="block text-muted-foreground hover:text-foreground transition-colors"
        >
          GitHub
        </a>
        <div class="flex items-center gap-2">
          <ThemeToggle />
          <span class="text-sm text-muted-foreground">Toggle theme</span>
        </div>
        <Button size="sm" variant="default" class="w-full">
          Join Waitlist
        </Button>
      </div>
    </div>
  </nav>
</template>
