// frontend/bin/commercial/app/pages/features.vue
<!-- Created by: TEAM-FE-009 -->
<!-- TEAM-FE-009: Implemented Features page assembly -->
<!-- TEAM-FE-010: Adapted for Nuxt -->
<script setup lang="ts">
import {
  FeaturesHero,
  CoreFeaturesTabs,
  CrossNodeOrchestration,
  IntelligentModelManagement,
  MultiBackendGPU,
  ErrorHandling,
  RealTimeProgress,
  SecurityIsolation,
  AdditionalFeaturesGrid,
  EmailCapture,
} from '~/stories'
</script>

<template>
  <div class="pt-16">
    <FeaturesHero />
    <CoreFeaturesTabs />
    <CrossNodeOrchestration />
    <IntelligentModelManagement />
    <MultiBackendGPU />
    <ErrorHandling />
    <RealTimeProgress />
    <SecurityIsolation />
    <AdditionalFeaturesGrid />
    <EmailCapture />
  </div>
</template>

// frontend/reference/v0/app/features/page.tsx
import { FeaturesHero } from "@/components/features/features-hero"
import { CoreFeaturesTabs } from "@/components/features/core-features-tabs"
import { CrossNodeOrchestration } from "@/components/features/cross-node-orchestration"
import { IntelligentModelManagement } from "@/components/features/intelligent-model-management"
import { MultiBackendGpu } from "@/components/features/multi-backend-gpu"
import { ErrorHandling } from "@/components/features/error-handling"
import { RealTimeProgress } from "@/components/features/real-time-progress"
import { SecurityIsolation } from "@/components/features/security-isolation"
import { AdditionalFeaturesGrid } from "@/components/features/additional-features-grid"
import { EmailCapture } from "@/components/email-capture"

export default function FeaturesPage() {
  return (
    <div className="pt-16">
      <FeaturesHero />
      <CoreFeaturesTabs />
      <CrossNodeOrchestration />
      <IntelligentModelManagement />
      <MultiBackendGpu />
      <ErrorHandling />
      <RealTimeProgress />
      <SecurityIsolation />
      <AdditionalFeaturesGrid />
      <EmailCapture />
    </div>
  )
}
