// frontend/libs/rbee-ui/src/organisms/Enterprise/EnterpriseSecurity/EnterpriseSecurity.tsx
import { Shield, Lock, Eye, Server, Clock, KeyRound } from 'lucide-react'
import Image from 'next/image'
import { SecurityCrate } from '@rbee/ui/molecules/SecurityCrate'

export function EnterpriseSecurity() {
  return (
    <section
      aria-labelledby="security-h2"
      className="relative border-b border-border bg-radial-glow px-6 py-24"
    >
      {/* Decorative background illustration */}
      <Image
        src="/decor/security-mesh.webp"
        width={1200}
        height={640}
        className="pointer-events-none absolute left-1/2 top-8 -z-10 hidden w-[52rem] -translate-x-1/2 opacity-15 blur-[0.5px] md:block"
        alt="Abstract dark security mesh with linked nodes and amber highlights, suggesting hash-chains, zero-trust, and time-bounded execution"
        aria-hidden="true"
      />

      <div className="relative z-10 mx-auto max-w-7xl">
        {/* Header */}
        <div className="animate-in fade-in-50 slide-in-from-bottom-2 mb-16 text-center duration-500">
          <p className="mb-2 text-sm font-medium text-primary/70">Defense-in-Depth</p>
          <h2 id="security-h2" className="mb-4 text-4xl font-bold text-foreground">
            Enterprise-Grade Security
          </h2>
          <p className="mx-auto max-w-3xl text-balance text-xl text-foreground/85">
            Six specialized security crates harden every layer—from auth and inputs to secrets, auditing,
            JWT lifecycle, and time-bounded execution.
          </p>
        </div>

        {/* Security Crates Grid */}
        <div className="animate-in fade-in-50 mb-12 grid gap-8 [animation-delay:120ms] lg:grid-cols-2">
          <SecurityCrate
            icon={<Lock className="h-6 w-6" aria-hidden="true" />}
            title="auth-min: Zero-Trust Authentication"
            subtitle="The Trickster Guardians"
            intro="Constant-time token checks stop CWE-208 leaks. Fingerprints let you log safely. Bind policies block accidental exposure."
            bullets={[
              'Timing-safe comparison (constant-time)',
              'Token fingerprinting (SHA-256)',
              'Bearer token parsing (RFC 6750)',
              'Bind policy enforcement',
            ]}
            docsHref="/docs/security/auth-min"
          />

          <SecurityCrate
            icon={<Eye className="h-6 w-6" aria-hidden="true" />}
            title="audit-logging: Compliance Engine"
            subtitle="Legally Defensible Proof"
            intro="Append-only audit trail with 32 event types. Hash-chain tamper detection. 7-year retention for GDPR."
            bullets={[
              'Immutable audit trail (append-only)',
              '32 event types across 7 categories',
              'Tamper detection (hash chains)',
              '7-year retention (GDPR)',
            ]}
            docsHref="/docs/security/audit-logging"
          />

          <SecurityCrate
            icon={<Shield className="h-6 w-6" aria-hidden="true" />}
            title="input-validation: First Line of Defense"
            subtitle="Trust No Input"
            intro="Prevents injection and exhaustion. Validates identifiers, prompts, paths—before execution."
            bullets={[
              'SQL injection prevention',
              'Command injection prevention',
              'Path traversal prevention',
              'Resource exhaustion prevention',
            ]}
            docsHref="/docs/security/input-validation"
          />

          <SecurityCrate
            icon={<Server className="h-6 w-6" aria-hidden="true" />}
            title="secrets-management: Credential Guardian"
            subtitle="Never in Environment"
            intro="File-scoped secrets with zeroization and systemd credentials. Timing-safe verification."
            bullets={[
              'File-based loading (not env vars)',
              'Memory zeroization on drop',
              'Permission validation (0600)',
              'Timing-safe verification',
            ]}
            docsHref="/docs/security/secrets-management"
          />

          <SecurityCrate
            icon={<KeyRound className="h-6 w-6" aria-hidden="true" />}
            title="jwt-guardian: Token Lifecycle Manager"
            subtitle="Stateless Yet Secure"
            intro="RS256 signature validation with clock-skew tolerance. Revocation lists and short-lived refresh tokens."
            bullets={[
              'RS256/ES256 signature validation',
              'Clock-skew tolerance (±5 min)',
              'Revocation list (Redis-backed)',
              'Short-lived refresh tokens (15 min)',
            ]}
            docsHref="/docs/security/jwt-guardian"
          />

          <SecurityCrate
            icon={<Clock className="h-6 w-6" aria-hidden="true" />}
            title="deadline-propagation: Performance Enforcer"
            subtitle="Every Millisecond Counts"
            intro="Propagates time budgets end-to-end. Aborts doomed work to protect SLOs."
            bullets={[
              'Deadline propagation (client → worker)',
              'Remaining time calculation',
              'Deadline enforcement (abort if insufficient)',
              'Timeout responses (504 Gateway Timeout)',
            ]}
            docsHref="/docs/security/deadline-propagation"
          />
        </div>

        {/* Security Guarantees */}
        <div className="animate-in fade-in-50 rounded-2xl border border-primary/20 bg-primary/5 p-8 [animation-delay:200ms]">
          <h3 className="mb-6 text-center text-2xl font-semibold text-foreground">Security Guarantees</h3>
          <div className="grid gap-6 md:grid-cols-3">
            <div className="text-center">
              <div className="mb-2 text-3xl font-bold text-primary" aria-label="Less than 10 percent timing variance">
                &lt; 10%
              </div>
              <div className="text-sm text-foreground/85">Timing variance (constant-time)</div>
            </div>
            <div className="text-center">
              <div className="mb-2 text-3xl font-bold text-primary" aria-label="100 percent token fingerprinting">
                100%
              </div>
              <div className="text-sm text-foreground/85">Token fingerprinting (no raw tokens)</div>
            </div>
            <div className="text-center">
              <div className="mb-2 text-3xl font-bold text-primary" aria-label="Zero memory leaks">
                Zero
              </div>
              <div className="text-sm text-foreground/85">Memory leaks (zeroization on drop)</div>
            </div>
          </div>
          <p className="mt-6 text-center text-xs text-muted-foreground">
            Figures represent default crate configurations; tune in policy for your environment.
          </p>
        </div>
      </div>
    </section>
  )
}

// frontend/libs/storybook/stories/organisms/EnterpriseSecurity/EnterpriseSecurity.vue
<!-- Created by: TEAM-FE-000 (Scaffolding) -->
<!-- TEAM-FE-008: Implemented EnterpriseSecurity -->
<script setup lang="ts">
import { Shield, Lock, Eye, Server, Clock } from 'lucide-vue-next'

interface SecurityCrate {
  icon: any
  title: string
  subtitle: string
  description: string
  features: string[]
}

interface Guarantee {
  value: string
  label: string
}

interface Props {
  title?: string
  subtitle?: string
  securityCrates?: SecurityCrate[]
  guarantees?: Guarantee[]
}

withDefaults(defineProps<Props>(), {
  title: 'Enterprise-Grade Security',
  subtitle:
    'Five specialized security crates provide defense-in-depth protection against the most sophisticated attacks.',
  securityCrates: () => [
    {
      icon: Lock,
      title: 'auth-min: Zero-Trust Authentication',
      subtitle: 'The Trickster Guardians',
      description:
        'Timing-safe token comparison prevents CWE-208 attacks. Token fingerprinting for safe logging. Bind policy enforcement prevents accidental exposure.',
      features: [
        'Timing-safe comparison (constant-time)',
        'Token fingerprinting (SHA-256)',
        'Bearer token parsing (RFC 6750)',
        'Bind policy enforcement',
      ],
    },
    {
      icon: Eye,
      title: 'audit-logging: Compliance Engine',
      subtitle: 'Legally Defensible Proof',
      description:
        'Immutable audit trail with 32 event types. Tamper detection via blockchain-style hash chains. 7-year retention for GDPR compliance.',
      features: [
        'Immutable audit trail (append-only)',
        '32 event types across 7 categories',
        'Tamper detection (hash chains)',
        '7-year retention (GDPR)',
      ],
    },
    {
      icon: Shield,
      title: 'input-validation: First Line of Defense',
      subtitle: 'Trust No Input',
      description:
        'Prevents injection attacks and resource exhaustion. Validates identifiers, model references, prompts, and paths before processing.',
      features: [
        'SQL injection prevention',
        'Command injection prevention',
        'Path traversal prevention',
        'Resource exhaustion prevention',
      ],
    },
    {
      icon: Server,
      title: 'secrets-management: Credential Guardian',
      subtitle: 'Never in Environment',
      description:
        'File-based secrets with memory zeroization. Systemd credentials support. Timing-safe verification prevents memory dump attacks.',
      features: [
        'File-based loading (not env vars)',
        'Memory zeroization on drop',
        'Permission validation (0600)',
        'Timing-safe verification',
      ],
    },
    {
      icon: Clock,
      title: 'deadline-propagation: Performance Enforcer',
      subtitle: 'Every Millisecond Counts',
      description:
        'Ensures rbee never wastes cycles on doomed work. Deadline propagation from client to worker. Aborts immediately when deadline exceeded.',
      features: [
        'Deadline propagation (client → worker)',
        'Remaining time calculation',
        'Deadline enforcement (abort if insufficient)',
        'Timeout responses (504 Gateway Timeout)',
      ],
    },
  ],
  guarantees: () => [
    { value: '< 10%', label: 'Timing variance (constant-time)' },
    { value: '100%', label: 'Token fingerprinting (no raw tokens)' },
    { value: 'Zero', label: 'Memory leaks (zeroization on drop)' },
  ],
})
</script>

<template>
  <section class="border-b border-border bg-background px-6 py-24">
    <div class="mx-auto max-w-7xl">
      <div class="mb-16 text-center">
        <h2 class="mb-4 text-4xl font-bold text-foreground">{{ title }}</h2>
        <p class="mx-auto max-w-3xl text-balance text-xl text-muted-foreground">
          {{ subtitle }}
        </p>
      </div>

      <div class="grid gap-8 lg:grid-cols-2">
        <div
          v-for="(crate, i) in securityCrates"
          :key="i"
          :class="[
            'rounded-lg border border-border bg-card p-8',
            i === securityCrates.length - 1 ? 'lg:col-span-2' : '',
          ]"
        >
          <div class="mb-4 flex items-center gap-3">
            <div class="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10">
              <component :is="crate.icon" class="h-6 w-6 text-primary" />
            </div>
            <div>
              <h3 class="text-xl font-bold text-foreground">{{ crate.title }}</h3>
              <p class="text-sm text-muted-foreground">{{ crate.subtitle }}</p>
            </div>
          </div>

          <p class="mb-4 leading-relaxed text-muted-foreground">
            {{ crate.description }}
          </p>

          <div :class="i === securityCrates.length - 1 ? 'grid gap-4 md:grid-cols-2' : 'space-y-2'">
            <div v-for="(feature, j) in crate.features" :key="j" class="flex items-start gap-2 text-sm text-muted-foreground">
              <span class="text-accent">✓</span>
              <span>{{ feature }}</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Security Guarantees -->
      <div class="mt-12 rounded-lg border border-primary/20 bg-primary/5 p-8">
        <h3 class="mb-6 text-center text-2xl font-semibold text-foreground">Security Guarantees</h3>
        <div class="grid gap-4 md:grid-cols-3">
          <div v-for="(guarantee, i) in guarantees" :key="i" class="text-center">
            <div class="mb-2 text-3xl font-bold text-primary">{{ guarantee.value }}</div>
            <div class="text-sm text-muted-foreground">{{ guarantee.label }}</div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
