// frontend/bin/commercial/app/pages/enterprise.vue
<!-- Created by: TEAM-FE-009 -->
<!-- TEAM-FE-009: Implemented Enterprise page assembly -->
<!-- TEAM-FE-010: Adapted for Nuxt -->
<script setup lang="ts">
import {
  EnterpriseHero,
  EnterpriseProblem,
  EnterpriseSolution,
  EnterpriseCompliance,
  EnterpriseSecurity,
  EnterpriseHowItWorks,
  EnterpriseUseCases,
  EnterpriseComparison,
  EnterpriseFeatures,
  EnterpriseTestimonials,
  EnterpriseCTA,
  EmailCapture,
  Footer,
} from 'rbee-storybook/stories'
</script>

<template>
  <main class="min-h-screen pt-16">
    <EnterpriseHero />
    <EmailCapture />
    <EnterpriseProblem />
    <EnterpriseSolution />
    <EnterpriseCompliance />
    <EnterpriseSecurity />
    <EnterpriseHowItWorks />
    <EnterpriseUseCases />
    <EnterpriseComparison />
    <EnterpriseFeatures />
    <EnterpriseTestimonials />
    <EnterpriseCTA />
    <Footer />
  </main>
</template>

// frontend/apps/commercial/app/enterprise/page.tsx
import {
	EmailCapture,
	EnterpriseComparison,
	EnterpriseCompliance,
	EnterpriseCTA,
	EnterpriseFeatures,
	EnterpriseHero,
	EnterpriseHowItWorks,
	EnterpriseProblem,
	EnterpriseSecurity,
	EnterpriseSolution,
	EnterpriseTestimonials,
	EnterpriseUseCases,
	Footer,
} from '@rbee/ui/organisms'

export default function EnterprisePage() {
	return (
		<main className="min-h-screen bg-slate-950">
			<EnterpriseHero />
			<EmailCapture />
			<EnterpriseProblem />
			<EnterpriseSolution />
			<EnterpriseCompliance />
			<EnterpriseSecurity />
			<EnterpriseHowItWorks />
			<EnterpriseUseCases />
			<EnterpriseComparison />
			<EnterpriseFeatures />
			<EnterpriseTestimonials />
			<EnterpriseCTA />
		</main>
	)
}
