// frontend/libs/storybook/stories/organisms/ComparisonSection/ComparisonSection.vue
<!-- Created by: TEAM-FE-000 (Scaffolding) -->
<!-- TEAM-FE-006: Implemented ComparisonSection component -->
<script setup lang="ts">
import { Check, X } from 'lucide-vue-next'

interface Props {
  title?: string
}

const props = withDefaults(defineProps<Props>(), {
  title: 'Why Developers Choose rbee',
})
</script>

<template>
  <section class="py-24 bg-secondary">
    <div class="container mx-auto px-4">
      <div class="max-w-4xl mx-auto text-center mb-16">
        <h2 class="text-4xl lg:text-5xl font-bold text-foreground mb-6 text-balance">
          {{ title }}
        </h2>
      </div>

      <div class="max-w-6xl mx-auto overflow-x-auto">
        <table class="w-full bg-card border border-border rounded-lg">
          <thead>
            <tr class="border-b border-border">
              <th class="text-left p-4 font-bold text-card-foreground">Feature</th>
              <th class="p-4 font-bold text-primary bg-accent">rbee</th>
              <th class="p-4 font-medium text-muted-foreground">OpenAI/Anthropic</th>
              <th class="p-4 font-medium text-muted-foreground">Ollama</th>
              <th class="p-4 font-medium text-muted-foreground">Runpod/Vast.ai</th>
            </tr>
          </thead>
          <tbody>
            <tr class="border-b border-border">
              <td class="p-4 font-medium text-card-foreground">Cost</td>
              <td class="p-4 text-center bg-accent">
                <div class="text-sm font-medium text-foreground">$0</div>
                <div class="text-xs text-muted-foreground">(your hardware)</div>
              </td>
              <td class="p-4 text-center text-sm text-muted-foreground">$20-100/mo per dev</td>
              <td class="p-4 text-center text-sm text-muted-foreground">$0</td>
              <td class="p-4 text-center text-sm text-muted-foreground">$0.50-2/hr</td>
            </tr>
            <tr class="border-b border-border">
              <td class="p-4 font-medium text-card-foreground">Privacy</td>
              <td class="p-4 text-center bg-accent">
                <Check class="h-5 w-5 text-green-600 mx-auto" />
                <div class="text-xs text-muted-foreground mt-1">Complete</div>
              </td>
              <td class="p-4 text-center">
                <X class="h-5 w-5 text-red-500 mx-auto" />
                <div class="text-xs text-muted-foreground mt-1">Limited</div>
              </td>
              <td class="p-4 text-center">
                <Check class="h-5 w-5 text-green-600 mx-auto" />
                <div class="text-xs text-muted-foreground mt-1">Complete</div>
              </td>
              <td class="p-4 text-center">
                <X class="h-5 w-5 text-red-500 mx-auto" />
                <div class="text-xs text-muted-foreground mt-1">Limited</div>
              </td>
            </tr>
            <tr class="border-b border-border">
              <td class="p-4 font-medium text-card-foreground">Multi-GPU</td>
              <td class="p-4 text-center bg-accent">
                <Check class="h-5 w-5 text-green-600 mx-auto" />
                <div class="text-xs text-muted-foreground mt-1">Orchestrated</div>
              </td>
              <td class="p-4 text-center text-sm text-muted-foreground">N/A</td>
              <td class="p-4 text-center">
                <div class="text-sm text-muted-foreground">Limited</div>
              </td>
              <td class="p-4 text-center">
                <Check class="h-5 w-5 text-green-600 mx-auto" />
              </td>
            </tr>
            <tr class="border-b border-border">
              <td class="p-4 font-medium text-card-foreground">OpenAI API</td>
              <td class="p-4 text-center bg-accent">
                <Check class="h-5 w-5 text-green-600 mx-auto" />
              </td>
              <td class="p-4 text-center">
                <Check class="h-5 w-5 text-green-600 mx-auto" />
              </td>
              <td class="p-4 text-center">
                <div class="text-sm text-muted-foreground">Partial</div>
              </td>
              <td class="p-4 text-center">
                <X class="h-5 w-5 text-red-500 mx-auto" />
              </td>
            </tr>
            <tr class="border-b border-border">
              <td class="p-4 font-medium text-card-foreground">Custom Routing</td>
              <td class="p-4 text-center bg-accent">
                <Check class="h-5 w-5 text-green-600 mx-auto" />
                <div class="text-xs text-muted-foreground mt-1">Rhai scripts</div>
              </td>
              <td class="p-4 text-center">
                <X class="h-5 w-5 text-red-500 mx-auto" />
              </td>
              <td class="p-4 text-center">
                <X class="h-5 w-5 text-red-500 mx-auto" />
              </td>
              <td class="p-4 text-center">
                <X class="h-5 w-5 text-red-500 mx-auto" />
              </td>
            </tr>
            <tr>
              <td class="p-4 font-medium text-card-foreground">Rate Limits</td>
              <td class="p-4 text-center bg-accent">
                <div class="text-sm font-medium text-green-600">None</div>
              </td>
              <td class="p-4 text-center">
                <div class="text-sm text-red-600">Yes</div>
              </td>
              <td class="p-4 text-center">
                <div class="text-sm font-medium text-green-600">None</div>
              </td>
              <td class="p-4 text-center">
                <div class="text-sm text-red-600">Yes</div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </section>
</template>

// frontend/packages/rbee-ui/src/organisms/Home/ComparisonSection/ComparisonSection.tsx
import { Button } from '@rbee/ui/atoms/Button'
import { SectionContainer } from '@rbee/ui/molecules'
import type { Provider, Row } from '@rbee/ui/molecules/Tables/MatrixTable'
import { MatrixTable } from '@rbee/ui/molecules/Tables/MatrixTable'
import { Check, X } from 'lucide-react'
import Link from 'next/link'

const columns: Provider[] = [
  { key: 'rbee', label: 'rbee', accent: true },
  { key: 'openai', label: 'OpenAI & Anthropic' },
  { key: 'ollama', label: 'Ollama' },
  { key: 'runpod', label: 'Runpod & Vast.ai' },
]

const rows: Row[] = [
  {
    feature: 'Total Cost',
    values: {
      rbee: '$0 (runs on your hardware)',
      openai: '$20–100/mo per dev',
      ollama: '$0',
      runpod: '$0.50–2/hr',
    },
  },
  {
    feature: 'Privacy / Data Residency',
    values: {
      rbee: true,
      openai: false,
      ollama: true,
      runpod: false,
    },
    note: 'Complete data control vs. limited',
  },
  {
    feature: 'Multi-GPU Utilization',
    values: {
      rbee: true,
      openai: 'N/A',
      ollama: 'Limited',
      runpod: true,
    },
  },
  {
    feature: 'OpenAI-Compatible API',
    values: {
      rbee: true,
      openai: true,
      ollama: 'Partial',
      runpod: false,
    },
  },
  {
    feature: 'Custom Routing Policies',
    values: {
      rbee: true,
      openai: false,
      ollama: false,
      runpod: false,
    },
  },
  {
    feature: 'Rate Limits / Quotas',
    values: {
      rbee: 'None',
      openai: 'Yes',
      ollama: 'None',
      runpod: 'Yes',
    },
  },
]

export function ComparisonSection() {
  return (
    <SectionContainer
      title="Why Developers Choose rbee"
      description="Local-first AI that's faster, private, and costs $0 on your hardware."
      bgVariant="secondary"
    >
      <div className="max-w-6xl mx-auto space-y-6 animate-in fade-in-50 duration-500">
        {/* Legend */}
        <div className="text-xs text-muted-foreground flex flex-wrap gap-4 justify-center">
          <span className="flex items-center gap-1.5">
            <Check className="h-3.5 w-3.5 text-chart-3" aria-hidden="true" />
            Available
          </span>
          <span className="flex items-center gap-1.5">
            <X className="h-3.5 w-3.5 text-destructive" aria-hidden="true" />
            Not available
          </span>
          <span>"Partial" = limited coverage</span>
        </div>

        {/* Comparison table */}
        <div className="rounded-xl ring-1 ring-border/60 bg-card overflow-hidden">
          <MatrixTable columns={columns} rows={rows} />
        </div>

        {/* Footer CTA */}
        <div className="mt-6 flex flex-col sm:flex-row gap-3 justify-center items-center">
          <p className="text-sm text-muted-foreground text-center sm:text-left font-sans">
            Bring your own GPUs, keep your data in-house.
          </p>
          <div className="flex gap-3">
            <Button asChild size="default">
              <Link href="/docs/quickstart">See Quickstart</Link>
            </Button>
            <Button asChild variant="ghost" size="default">
              <Link href="/docs/architecture">Architecture</Link>
            </Button>
          </div>
        </div>
      </div>
    </SectionContainer>
  )
}
