// frontend/libs/storybook/stories/organisms/DevelopersHowItWorks/DevelopersHowItWorks.vue
<!-- Created by: TEAM-FE-000 (Scaffolding) -->
<!-- TEAM-FE-005: Implemented DevelopersHowItWorks -->
<script setup lang="ts">
interface Step {
  number: number
  title: string
  code: string[]
  language?: string
}

interface Props {
  title?: string
  steps?: Step[]
}

withDefaults(defineProps<Props>(), {
  title: 'From Zero to AI Infrastructure in 15 Minutes',
  steps: () => [
    {
      number: 1,
      title: 'Install rbee',
      code: ['curl -sSL https://rbee.dev/install.sh | sh', 'rbee-keeper daemon start'],
      language: 'terminal',
    },
    {
      number: 2,
      title: 'Add Your Machines',
      code: [
        'rbee-keeper setup add-node --name workstation --ssh-host 192.168.1.10',
        'rbee-keeper setup add-node --name mac --ssh-host 192.168.1.20',
      ],
      language: 'terminal',
    },
    {
      number: 3,
      title: 'Configure Your IDE',
      code: [
        'export OPENAI_API_BASE=http://localhost:8080/v1',
        '# Now Zed, Cursor, or any OpenAI-compatible tool works!',
      ],
      language: 'terminal',
    },
    {
      number: 4,
      title: 'Build AI Agents',
      code: [
        "import { invoke } from '@llama-orch/utils';",
        '',
        "const code = await invoke({",
        "  prompt: 'Generate API from schema',",
        "  model: 'llama-3.1-70b'",
        '});',
      ],
      language: 'TypeScript',
    },
  ],
})
</script>

<template>
  <section class="border-b border-border bg-secondary/30 py-24">
    <div class="mx-auto max-w-7xl px-6 lg:px-8">
      <div class="mx-auto max-w-2xl text-center">
        <h2 class="mb-4 text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
          {{ title }}
        </h2>
      </div>

      <div class="mx-auto mt-16 max-w-4xl space-y-12">
        <div v-for="step in steps" :key="step.number" class="flex gap-6">
          <div
            class="flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-lg bg-primary text-xl font-bold text-primary-foreground"
          >
            {{ step.number }}
          </div>
          <div class="flex-1">
            <h3 class="mb-3 text-xl font-semibold text-foreground">{{ step.title }}</h3>
            <div class="overflow-hidden rounded-lg border border-border bg-secondary">
              <div class="border-b border-border bg-muted px-4 py-2">
                <span class="text-sm text-muted-foreground">{{ step.language || 'code' }}</span>
              </div>
              <div class="p-4 font-mono text-sm text-foreground">
                <div v-for="(line, index) in step.code" :key="index" :class="line.startsWith('#') ? 'text-muted-foreground' : ''">
                  {{ line }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

// frontend/bin/commercial/components/developers/developers-how-it-works.tsx
export function DevelopersHowItWorks() {
  return (
    <section className="border-b border-border bg-secondary py-24">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="mx-auto max-w-2xl text-center">
          <h2 className="mb-4 text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
            From Zero to AI Infrastructure in 15 Minutes
          </h2>
        </div>

        <div className="mx-auto mt-16 max-w-4xl space-y-12">
          {/* Step 1 */}
          <div className="flex gap-6">
            <div className="flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-lg bg-primary text-xl font-bold text-primary-foreground">
              1
            </div>
            <div className="flex-1">
              <h3 className="mb-3 text-xl font-semibold text-card-foreground">Install rbee</h3>
              <div className="overflow-hidden rounded-lg border border-border bg-card">
                <div className="border-b border-border bg-muted px-4 py-2">
                  <span className="text-sm text-muted-foreground">terminal</span>
                </div>
                <div className="p-4 font-mono text-sm text-foreground">
                  <div>curl -sSL https://rbee.dev/install.sh | sh</div>
                  <div className="text-muted-foreground">rbee-keeper daemon start</div>
                </div>
              </div>
            </div>
          </div>

          {/* Step 2 */}
          <div className="flex gap-6">
            <div className="flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-lg bg-primary text-xl font-bold text-primary-foreground">
              2
            </div>
            <div className="flex-1">
              <h3 className="mb-3 text-xl font-semibold text-card-foreground">Add Your Machines</h3>
              <div className="overflow-hidden rounded-lg border border-border bg-card">
                <div className="border-b border-border bg-muted px-4 py-2">
                  <span className="text-sm text-muted-foreground">terminal</span>
                </div>
                <div className="p-4 font-mono text-sm text-foreground">
                  <div>rbee-keeper setup add-node --name workstation --ssh-host 192.168.1.10</div>
                  <div className="text-muted-foreground">rbee-keeper setup add-node --name mac --ssh-host 192.168.1.20</div>
                </div>
              </div>
            </div>
          </div>

          {/* Step 3 */}
          <div className="flex gap-6">
            <div className="flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-lg bg-primary text-xl font-bold text-primary-foreground">
              3
            </div>
            <div className="flex-1">
              <h3 className="mb-3 text-xl font-semibold text-card-foreground">Configure Your IDE</h3>
              <div className="overflow-hidden rounded-lg border border-border bg-card">
                <div className="border-b border-border bg-muted px-4 py-2">
                  <span className="text-sm text-muted-foreground">terminal</span>
                </div>
                <div className="p-4 font-mono text-sm text-foreground">
                  <div>
                    <span className="text-chart-2">export</span> OPENAI_API_BASE=http://localhost:8080/v1
                  </div>
                  <div className="text-muted-foreground"># Now Zed, Cursor, or any OpenAI-compatible tool works!</div>
                </div>
              </div>
            </div>
          </div>

          {/* Step 4 */}
          <div className="flex gap-6">
            <div className="flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-lg bg-primary text-xl font-bold text-primary-foreground">
              4
            </div>
            <div className="flex-1">
              <h3 className="mb-3 text-xl font-semibold text-card-foreground">Build AI Agents</h3>
              <div className="overflow-hidden rounded-lg border border-border bg-card">
                <div className="border-b border-border bg-muted px-4 py-2">
                  <span className="text-sm text-muted-foreground">TypeScript</span>
                </div>
                <div className="p-4 font-mono text-sm text-foreground">
                  <div>
                    <span className="text-chart-4">import</span> {"{"} invoke {"}"}{" "}
                    <span className="text-chart-4">from</span>{" "}
                    <span className="text-primary">&apos;@llama-orch/utils&apos;</span>;
                  </div>
                  <div className="mt-2">
                    <span className="text-chart-2">const</span> code = <span className="text-chart-2">await</span>{" "}
                    <span className="text-chart-3">invoke</span>({"{"}
                  </div>
                  <div className="pl-4">
                    prompt: <span className="text-primary">&apos;Generate API from schema&apos;</span>,
                  </div>
                  <div className="pl-4">
                    model: <span className="text-primary">&apos;llama-3.1-70b&apos;</span>
                  </div>
                  <div>{"});"}</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
