// frontend/bin/commercial/components/organisms/FeaturesSection/FeaturesSection.tsx
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/atoms/Tabs/Tabs'
import { Code, Cpu, Gauge, Zap } from "lucide-react"
import { SectionContainer, CodeBlock, BenefitCallout } from '@/components/molecules'

export function FeaturesSection() {
  return (
    <SectionContainer
      title="Enterprise-Grade Features. Homelab Simplicity."
      bgVariant="secondary"
    >

        <div className="max-w-5xl mx-auto">
          <Tabs defaultValue="api" className="w-full">
            <TabsList className="grid w-full grid-cols-2 lg:grid-cols-4 h-auto">
              <TabsTrigger value="api" className="flex items-center gap-2 py-3">
                <Code className="h-4 w-4" />
                <span className="hidden sm:inline">OpenAI-Compatible</span>
                <span className="sm:hidden">API</span>
              </TabsTrigger>
              <TabsTrigger value="gpu" className="flex items-center gap-2 py-3">
                <Cpu className="h-4 w-4" />
                <span className="hidden sm:inline">Multi-GPU</span>
                <span className="sm:hidden">GPU</span>
              </TabsTrigger>
              <TabsTrigger value="scheduler" className="flex items-center gap-2 py-3">
                <Gauge className="h-4 w-4" />
                <span className="hidden sm:inline">Scheduler</span>
                <span className="sm:hidden">Rhai</span>
              </TabsTrigger>
              <TabsTrigger value="sse" className="flex items-center gap-2 py-3">
                <Zap className="h-4 w-4" />
                <span className="hidden sm:inline">Real‑time</span>
                <span className="sm:hidden">SSE</span>
              </TabsTrigger>
            </TabsList>

            <TabsContent value="api" className="mt-8">
              <div className="bg-card border border-border rounded-lg p-8 space-y-6">
                <div>
                  <h3 className="text-2xl font-bold text-card-foreground mb-3">OpenAI-Compatible API</h3>
                  <p className="text-muted-foreground leading-relaxed">
                    Drop-in replacement for OpenAI API. Works with Zed, Cursor, Continue, and any tool that supports
                    OpenAI.
                  </p>
                </div>

                <CodeBlock
                  language="bash"
                  code={`# Before: Using OpenAI
export OPENAI_API_KEY=sk-...

# After: Using rbee (same code!)
export OPENAI_API_BASE=http://localhost:8080/v1`}
                />

                <BenefitCallout
                  variant="success"
                  text="No code changes. Just point to localhost."
                />
              </div>
            </TabsContent>

            <TabsContent value="gpu" className="mt-8">
              <div className="bg-card border border-border rounded-lg p-8 space-y-6">
                <div>
                  <h3 className="text-2xl font-bold text-card-foreground mb-3">Multi-GPU Orchestration</h3>
                  <p className="text-muted-foreground leading-relaxed">
                    Orchestrate across the CUDA, Metal, and CPU backends you configure. Use every GPU you own.
                  </p>
                </div>

                <div className="space-y-3">
                  <div className="flex items-center gap-3">
                    <div className="flex-shrink-0 w-32 text-sm text-muted-foreground">RTX 4090 #1</div>
                    <div className="flex-1 h-8 bg-muted rounded-full overflow-hidden">
                      <div className="h-full bg-primary flex items-center justify-end pr-2" style={{ width: "92%" }}>
                        <span className="text-xs text-white font-medium">92%</span>
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-3">
                    <div className="flex-shrink-0 w-32 text-sm text-muted-foreground">RTX 4090 #2</div>
                    <div className="flex-1 h-8 bg-muted rounded-full overflow-hidden">
                      <div className="h-full bg-primary flex items-center justify-end pr-2" style={{ width: "88%" }}>
                        <span className="text-xs text-white font-medium">88%</span>
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-3">
                    <div className="flex-shrink-0 w-32 text-sm text-muted-foreground">M2 Ultra</div>
                    <div className="flex-1 h-8 bg-muted rounded-full overflow-hidden">
                      <div className="h-full bg-primary flex items-center justify-end pr-2" style={{ width: "76%" }}>
                        <span className="text-xs text-white font-medium">76%</span>
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-3">
                    <div className="flex-shrink-0 w-32 text-sm text-muted-foreground">CPU Backend</div>
                    <div className="flex-1 h-8 bg-muted rounded-full overflow-hidden">
                      <div className="h-full bg-chart-2 flex items-center justify-end pr-2" style={{ width: "34%" }}>
                        <span className="text-xs text-white font-medium">34%</span>
                      </div>
                    </div>
                  </div>
                </div>

                <BenefitCallout
                  variant="info"
                  text="10x throughput by using all your hardware."
                />
              </div>
            </TabsContent>

            <TabsContent value="scheduler" className="mt-8">
              <div className="bg-card border border-border rounded-lg p-8 space-y-6">
                <div>
                  <h3 className="text-2xl font-bold text-card-foreground mb-3">Programmable Rhai Scheduler</h3>
                  <p className="text-muted-foreground leading-relaxed">
                    Write custom routing logic in Rhai. Route large models to multi-GPU setups, image generation to
                    CUDA, everything else to cheapest.
                  </p>
                </div>

                <CodeBlock
                  language="rust"
                  code={`// Custom routing logic
if task.model.contains("70b") {
  route_to("multi-gpu-cluster")
} else if task.type == "image" {
  route_to("cuda-only")
} else {
  route_to("cheapest")
}`}
                />

                <BenefitCallout
                  variant="primary"
                  text="Optimize for cost, latency, or compliance—your rules."
                />
              </div>
            </TabsContent>

            <TabsContent value="sse" className="mt-8">
              <div className="bg-card border border-border rounded-lg p-8 space-y-6">
                <div>
                  <h3 className="text-2xl font-bold text-card-foreground mb-3">Task-Based API with SSE</h3>
                  <p className="text-muted-foreground leading-relaxed">
                    Real‑time progress updates. See model loading, token generation, and cost tracking as it happens.
                  </p>
                </div>

                <CodeBlock
                  language="json"
                  code={`→ event: task.created
{ "id": "task_123", "status": "pending" }

→ event: model.loading
{ "progress": 0.45, "eta": "2.1s" }

→ event: token.generated
{ "token": "const", "total": 1 }

→ event: token.generated
{ "token": " api", "total": 2 }`}
                />

                <BenefitCallout text="Full visibility into every inference job." />
              </div>
            </TabsContent>
          </Tabs>
        </div>
      </SectionContainer>
  )
}

// frontend/libs/storybook/stories/organisms/FeaturesSection/FeaturesSection.vue
<!-- Created by: TEAM-FE-000 (Scaffolding) -->
<!-- TEAM-FE-006: Implemented FeaturesSection component -->
<script setup lang="ts">
import { ref, computed } from 'vue'
import { Code, Cpu, Gauge, Zap } from 'lucide-vue-next'
import Tabs from '../../atoms/Tabs/Tabs.vue'
import TabsList from '../../atoms/Tabs/TabsList.vue'
import TabsTrigger from '../../atoms/Tabs/TabsTrigger.vue'
import TabsContent from '../../atoms/Tabs/TabsContent.vue'

interface Props {
  title?: string
}

const props = withDefaults(defineProps<Props>(), {
  title: 'Enterprise-Grade Features. Homelab Simplicity.',
})

const activeTab = ref('api')
</script>

<template>
  <section class="py-24 bg-secondary">
    <div class="container mx-auto px-4">
      <div class="max-w-4xl mx-auto text-center mb-16">
        <h2 class="text-4xl lg:text-5xl font-bold text-foreground mb-6 text-balance">
          {{ title }}
        </h2>
      </div>

      <div class="max-w-5xl mx-auto">
        <Tabs v-model="activeTab" default-value="api" class="w-full">
          <TabsList class="grid w-full grid-cols-2 lg:grid-cols-4 h-auto">
            <TabsTrigger value="api" class="flex items-center gap-2 py-3">
              <Code class="h-4 w-4" />
              <span class="hidden sm:inline">OpenAI API</span>
              <span class="sm:hidden">API</span>
            </TabsTrigger>
            <TabsTrigger value="gpu" class="flex items-center gap-2 py-3">
              <Cpu class="h-4 w-4" />
              <span class="hidden sm:inline">Multi-GPU</span>
              <span class="sm:hidden">GPU</span>
            </TabsTrigger>
            <TabsTrigger value="scheduler" class="flex items-center gap-2 py-3">
              <Gauge class="h-4 w-4" />
              <span class="hidden sm:inline">Scheduler</span>
              <span class="sm:hidden">Rhai</span>
            </TabsTrigger>
            <TabsTrigger value="sse" class="flex items-center gap-2 py-3">
              <Zap class="h-4 w-4" />
              <span class="hidden sm:inline">Real-time</span>
              <span class="sm:hidden">SSE</span>
            </TabsTrigger>
          </TabsList>

          <TabsContent value="api" class="mt-8">
            <div class="bg-card border border-border rounded-lg p-8 space-y-6">
              <div>
                <h3 class="text-2xl font-bold text-card-foreground mb-3">OpenAI-Compatible API</h3>
                <p class="text-muted-foreground leading-relaxed">
                  Drop-in replacement for OpenAI API. Works with Zed, Cursor, Continue, and any tool that supports OpenAI.
                </p>
              </div>

              <div class="bg-card border border-border rounded-lg p-6 font-mono text-sm">
                <div class="text-muted-foreground"># Before: Using OpenAI</div>
                <div class="text-green-600 mt-2">export OPENAI_API_KEY=sk-...</div>
                <div class="text-muted-foreground mt-4"># After: Using rbee (same code!)</div>
                <div class="text-green-600 mt-2">export OPENAI_API_BASE=http://localhost:8080/v1</div>
              </div>

              <div class="bg-green-100 border border-green-200 rounded-lg p-4">
                <p class="text-green-900 font-medium">✓ No code changes. Just point to localhost.</p>
              </div>
            </div>
          </TabsContent>

          <TabsContent value="gpu" class="mt-8">
            <div class="bg-card border border-border rounded-lg p-8 space-y-6">
              <div>
                <h3 class="text-2xl font-bold text-card-foreground mb-3">Multi-GPU Orchestration</h3>
                <p class="text-muted-foreground leading-relaxed">
                  Automatically distribute workloads across CUDA, Metal, and CPU backends. Use every GPU you own.
                </p>
              </div>

              <div class="space-y-3">
                <div class="flex items-center gap-3">
                  <div class="flex-shrink-0 w-32 text-sm text-muted-foreground">RTX 4090 #1</div>
                  <div class="flex-1 h-8 bg-muted rounded-full overflow-hidden">
                    <div class="h-full bg-primary flex items-center justify-end pr-2" style="width: 92%">
                      <span class="text-xs text-primary-foreground font-medium">92%</span>
                    </div>
                  </div>
                </div>
                <div class="flex items-center gap-3">
                  <div class="flex-shrink-0 w-32 text-sm text-muted-foreground">RTX 4090 #2</div>
                  <div class="flex-1 h-8 bg-muted rounded-full overflow-hidden">
                    <div class="h-full bg-primary flex items-center justify-end pr-2" style="width: 88%">
                      <span class="text-xs text-primary-foreground font-medium">88%</span>
                    </div>
                  </div>
                </div>
                <div class="flex items-center gap-3">
                  <div class="flex-shrink-0 w-32 text-sm text-muted-foreground">M2 Ultra</div>
                  <div class="flex-1 h-8 bg-muted rounded-full overflow-hidden">
                    <div class="h-full bg-primary flex items-center justify-end pr-2" style="width: 76%">
                      <span class="text-xs text-primary-foreground font-medium">76%</span>
                    </div>
                  </div>
                </div>
                <div class="flex items-center gap-3">
                  <div class="flex-shrink-0 w-32 text-sm text-muted-foreground">CPU Fallback</div>
                  <div class="flex-1 h-8 bg-muted rounded-full overflow-hidden">
                    <div class="h-full bg-blue-400 flex items-center justify-end pr-2" style="width: 34%">
                      <span class="text-xs text-white font-medium">34%</span>
                    </div>
                  </div>
                </div>
              </div>

              <div class="bg-blue-100 border border-blue-200 rounded-lg p-4">
                <p class="text-blue-900 font-medium">✓ 10x throughput by using all your hardware.</p>
              </div>
            </div>
          </TabsContent>

          <TabsContent value="scheduler" class="mt-8">
            <div class="bg-card border border-border rounded-lg p-8 space-y-6">
              <div>
                <h3 class="text-2xl font-bold text-card-foreground mb-3">Programmable Rhai Scheduler</h3>
                <p class="text-muted-foreground leading-relaxed">
                  Write custom routing logic in Rhai. Route large models to multi-GPU setups, image generation to CUDA, everything else to cheapest.
                </p>
              </div>

              <div class="bg-card border border-border rounded-lg p-6 font-mono text-sm">
                <div class="text-muted-foreground">// Custom routing logic</div>
                <div class="text-primary mt-2">if <span class="text-foreground">task.model.contains("70b") {</span></div>
                <div class="text-foreground pl-4">route_to(<span class="text-green-600">"multi-gpu-cluster"</span>)</div>
                <div class="text-foreground">}</div>
                <div class="text-primary mt-2">else if <span class="text-foreground">task.type == "image" {</span></div>
                <div class="text-foreground pl-4">route_to(<span class="text-green-600">"cuda-only"</span>)</div>
                <div class="text-foreground">}</div>
                <div class="text-primary mt-2">else <span class="text-foreground">{</span></div>
                <div class="text-foreground pl-4">route_to(<span class="text-green-600">"cheapest"</span>)</div>
                <div class="text-foreground">}</div>
              </div>

              <div class="bg-accent border border-border rounded-lg p-4">
                <p class="text-accent-foreground font-medium">✓ Optimize for cost, latency, or compliance—your rules.</p>
              </div>
            </div>
          </TabsContent>

          <TabsContent value="sse" class="mt-8">
            <div class="bg-card border border-border rounded-lg p-8 space-y-6">
              <div>
                <h3 class="text-2xl font-bold text-card-foreground mb-3">Task-Based API with SSE</h3>
                <p class="text-muted-foreground leading-relaxed">
                  Real-time progress updates. See model loading, token generation, and cost tracking as it happens.
                </p>
              </div>

              <div class="bg-card border border-border rounded-lg p-6 font-mono text-sm space-y-2">
                <div class="text-muted-foreground">→ event: task.created</div>
                <div class="text-foreground pl-4">{ "id": "task_123", "status": "pending" }</div>
                <div class="text-muted-foreground mt-2">→ event: model.loading</div>
                <div class="text-foreground pl-4">{ "progress": 0.45, "eta": "2.1s" }</div>
                <div class="text-muted-foreground mt-2">→ event: token.generated</div>
                <div class="text-foreground pl-4">{ "token": "const", "total": 1 }</div>
                <div class="text-muted-foreground mt-2">→ event: token.generated</div>
                <div class="text-foreground pl-4">{ "token": " api", "total": 2 }</div>
              </div>

              <div class="bg-muted border border-border rounded-lg p-4">
                <p class="text-foreground font-medium">✓ Full visibility into every inference job.</p>
              </div>
            </div>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  </section>
</template>
