// frontend/bin/commercial/app/stories/organisms/EmailCapture/EmailCapture.vue
<!-- Created by: TEAM-FE-000 (Scaffolding) -->
<!-- TEAM-FE-CONSOLIDATE: Implemented EmailCapture with design tokens -->
<script setup lang="ts">
import { ref } from 'vue'
import { Button, Input } from '~/stories'
import { Mail, CheckCircle2, Github } from 'lucide-vue-next'

interface Props {
  title?: string
  description?: string
  statusBadge?: string
  privacyText?: string
  githubText?: string
  githubUrl?: string
}

const props = withDefaults(defineProps<Props>(), {
  title: 'Be the First to Know',
  description: 'rbee is actively being built. Join our waitlist to get early access, updates on development progress, and exclusive launch benefits.',
  statusBadge: 'Currently in Development (M0 - 68% Complete)',
  privacyText: 'No spam. Unsubscribe anytime. We respect your privacy.',
  githubText: 'Star us on GitHub',
  githubUrl: 'https://github.com/veighnsche/llama-orch',
})

const email = ref('')
const submitted = ref(false)

const handleSubmit = (e: Event) => {
  e.preventDefault()
  // TODO: Wire up to actual email service (backend integration)
  console.log('Email submitted:', email.value)
  submitted.value = true
  setTimeout(() => {
    submitted.value = false
    email.value = ''
  }, 3000)
}
</script>

<template>
  <section class="py-24 bg-gradient-to-br from-background via-secondary to-background">
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
      <div class="inline-flex items-center gap-2 px-4 py-2 bg-primary/10 border border-primary/20 rounded-full text-primary text-sm font-medium mb-6">
        <span class="relative flex h-2 w-2">
          <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary opacity-75"></span>
          <span class="relative inline-flex rounded-full h-2 w-2 bg-primary"></span>
        </span>
        {{ statusBadge }}
      </div>

      <h2 class="text-4xl md:text-5xl font-bold text-foreground mb-6">{{ title }}</h2>

      <p class="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto leading-relaxed">
        {{ description }}
      </p>

      <form v-if="!submitted" @submit="handleSubmit" class="flex flex-col sm:flex-row gap-4 max-w-md mx-auto">
        <div class="flex-1 relative">
          <Mail class="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
          <Input
            v-model="email"
            type="email"
            placeholder="your@email.com"
            required
            class="pl-10 h-12"
          />
        </div>
        <Button
          type="submit"
          size="lg"
          variant="default"
          class="h-12 px-8"
        >
          Join Waitlist
        </Button>
      </form>

      <div v-else class="flex items-center justify-center gap-2 text-primary text-lg">
        <CheckCircle2 :size="24" />
        <span>Thanks! We'll keep you updated.</span>
      </div>

      <p class="text-sm text-muted-foreground mt-6">{{ privacyText }}</p>

      <div class="mt-12 pt-12 border-t border-border">
        <p class="text-muted-foreground mb-4">Want to contribute or follow development?</p>
        <a
          :href="githubUrl"
          target="_blank"
          rel="noopener noreferrer"
          class="inline-flex items-center gap-2 text-primary hover:text-primary/80 transition-colors font-medium"
        >
          <Github :size="20" />
          {{ githubText }}
        </a>
      </div>
    </div>
  </section>
</template>

// frontend/packages/rbee-ui/src/organisms/EmailCapture/EmailCapture.tsx
"use client";

import { Badge } from "@rbee/ui/atoms/Badge";
import { Button } from "@rbee/ui/atoms/Button";
import { Input } from "@rbee/ui/atoms/Input";
import { BeeGlyph, HomelabBee } from "@rbee/ui/icons";
import { CheckCircle2, GitBranch, Lock, Mail } from "lucide-react";
import type React from "react";
import { useState } from "react";

export function EmailCapture() {
  const [email, setEmail] = useState("");
  const [submitted, setSubmitted] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    // TODO: Wire up to actual email service
    console.log("Email submitted:", email);
    setSubmitted(true);
    setTimeout(() => {
      setSubmitted(false);
      setEmail("");
    }, 3000);
  };

  return (
    <section className="relative isolate py-28 bg-background">
      {/* Decorative bee glyphs */}
      <BeeGlyph className="absolute top-16 left-[8%] opacity-5 pointer-events-none" />
      <BeeGlyph className="absolute bottom-20 right-[10%] opacity-5 pointer-events-none" />

      <div className="relative max-w-3xl mx-auto px-6 text-center">
        {/* Status badge */}
        <Badge
          variant="outline"
          className="mb-4 inline-flex items-center gap-2 border-primary/20 bg-primary/10 px-3 py-1 animate-in fade-in slide-in-from-bottom-2 duration-500"
          style={{ animationDelay: "100ms" }}
        >
          <span className="relative flex h-2 w-2">
            <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-primary opacity-75"></span>
            <span className="relative inline-flex h-2 w-2 rounded-full bg-primary"></span>
          </span>
          <span className="text-xs font-medium uppercase tracking-wider text-primary">
            In Development · M0 · 68%
          </span>
        </Badge>

        {/* Headline */}
        <h2
          className="text-5xl md:text-6xl font-bold tracking-tight text-foreground mb-5 animate-in fade-in slide-in-from-bottom-2 duration-500"
          style={{ animationDelay: "300ms" }}
        >
          Get Updates. Own Your AI.
        </h2>

        {/* Subhead */}
        <p
          className="text-lg md:text-xl text-muted-foreground mb-8 leading-relaxed max-w-2xl mx-auto animate-in fade-in slide-in-from-bottom-2 duration-500"
          style={{ animationDelay: "450ms" }}
        >
          Join the rbee waitlist to get early access, build notes, and launch
          perks for running AI on your own hardware.
        </p>

        {/* Supportive visual - homelab illustration */}
        <HomelabBee
          size={960}
          className="pointer-events-none absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-[52%] opacity-20"
          aria-hidden="true"
        />

        {/* Form or success state */}
        {!submitted ? (
          <form onSubmit={handleSubmit} className="mx-auto max-w-xl">
            <div className="flex flex-col sm:flex-row items-stretch gap-3">
              <div className="relative flex-1">
                <label htmlFor="waitlist-email" className="sr-only">
                  Email address
                </label>
                <Mail
                  className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground/80"
                  aria-hidden="true"
                  focusable="false"
                />
                <Input
                  id="waitlist-email"
                  type="email"
                  placeholder="you@company.com"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                  className="h-12 pl-10 bg-card/80 border-border/70 text-foreground placeholder:text-muted-foreground focus-visible:ring-2 focus-visible:ring-primary/40 transition-shadow data-[invalid=true]:border-destructive/60 data-[invalid=true]:bg-destructive/5"
                />
              </div>
              <Button
                type="submit"
                className="h-12 px-7 bg-primary text-primary-foreground font-semibold rounded-xl shadow-sm hover:translate-y-[-1px] hover:shadow-md transition-transform"
              >
                Join Waitlist
              </Button>
            </div>

            {/* Trust microcopy */}
            <div className="mt-3 text-sm text-muted-foreground flex items-center justify-center gap-2">
              <Lock
                className="w-3.5 h-3.5 text-muted-foreground/70"
                aria-hidden="true"
                focusable="false"
              />
              <span>No spam. Unsubscribe anytime.</span>
            </div>
          </form>
        ) : (
          <div
            className="inline-flex items-center gap-2 text-chart-3 text-base md:text-lg font-medium bg-card/60 border border-border/60 rounded-xl px-4 py-3 shadow-xs"
            role="status"
            aria-live="polite"
          >
            <CheckCircle2
              className="w-5 h-5"
              aria-hidden="true"
              focusable="false"
            />
            <span>Thanks! You're on the list — we'll keep you posted.</span>
          </div>
        )}

        {/* Community footer band */}
        <div className="mt-14 pt-8">
          {/* Gradient divider */}
          <div className="h-px w-full mx-auto bg-gradient-to-r from-transparent via-border to-transparent" />

          <p className="text-sm text-muted-foreground mt-6">
            Follow progress & contribute on GitHub
          </p>

          <a
            href="https://github.com/veighnsche/llama-orch"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 mt-3 text-primary font-medium hover:text-primary/90 transition-colors"
          >
            <GitBranch
              className="w-5 h-5"
              aria-hidden="true"
              focusable="false"
            />
            <span>View Repository</span>
          </a>

          <p className="text-xs text-muted-foreground/80 mt-2">
            Weekly dev notes. Roadmap issues tagged M0–M2.
          </p>
        </div>
      </div>
    </section>
  );
}
