// frontend/packages/rbee-ui/src/organisms/Enterprise/EnterpriseCompliance/EnterpriseCompliance.tsx
import { Button, Card, CardContent } from '@rbee/ui/atoms'
import { BulletListItem, IconCardHeader } from '@rbee/ui/molecules'
import { Globe, Lock, Shield } from 'lucide-react'
import Image from 'next/image'
import Link from 'next/link'

export function EnterpriseCompliance() {
  return (
    <section
      id="compliance"
      aria-labelledby="compliance-h2"
      className="relative border-b border-border bg-radial-glow px-6 py-24"
    >
      {/* Decorative background illustration */}
      <Image
        src="/decor/compliance-ledger.webp"
        width={1200}
        height={640}
        className="pointer-events-none absolute left-1/2 top-6 -z-10 hidden w-[50rem] -translate-x-1/2 opacity-15 blur-[0.5px] md:block"
        alt="Abstract EU-blue ledger lines with checkpoint nodes; evokes immutable audit trails, GDPR alignment, SOC2 controls, ISO 27001 ISMS"
        aria-hidden="true"
      />

      <div className="relative z-10 mx-auto max-w-7xl">
        {/* Header */}
        <div className="animate-in fade-in-50 slide-in-from-bottom-2 mb-16 text-center duration-500">
          <p className="mb-2 text-sm font-medium text-primary/80">Security & Certifications</p>
          <h2 id="compliance-h2" className="mb-4 text-4xl font-bold text-foreground">
            Compliance by Design
          </h2>
          <p className="mx-auto max-w-3xl text-balance text-xl text-foreground/85">
            Built from the ground up to meet GDPR, SOC2, and ISO 27001 requirements—security is engineered in, not
            bolted on.
          </p>
        </div>

        {/* Three Pillars */}
        <div className="animate-in fade-in-50 mb-12 grid gap-8 [animation-delay:120ms] lg:grid-cols-3">
          {/* GDPR Pillar */}
          <Card
            className="h-full rounded-2xl border-border bg-card/60 p-8 transition-shadow hover:shadow-lg"
            aria-labelledby="compliance-gdpr"
          >
            <IconCardHeader icon={Globe} title="GDPR" subtitle="EU Regulation" titleId="compliance-gdpr" />
            <CardContent className="p-0">
              <ul className="space-y-3">
                <BulletListItem variant="check" title="7-year audit retention (Art. 30)" />
                <BulletListItem variant="check" title="Data access records (Art. 15)" />
                <BulletListItem variant="check" title="Erasure tracking (Art. 17)" />
                <BulletListItem variant="check" title="Consent management (Art. 7)" />
                <BulletListItem variant="check" title="Data residency controls (Art. 44)" />
                <BulletListItem variant="check" title="Breach notification (Art. 33)" />
              </ul>
              <div className="mt-6">
                <div className="rounded-lg border border-chart-3/50 bg-chart-3/10 p-4">
                  <div className="mb-2 font-semibold text-chart-3">Compliance Endpoints</div>
                  <div className="space-y-1 font-mono text-xs text-foreground/85">
                    <div>GET /v2/compliance/data-access</div>
                    <div>POST /v2/compliance/data-export</div>
                    <div>POST /v2/compliance/data-deletion</div>
                    <div>GET /v2/compliance/audit-trail</div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* SOC2 Pillar */}
          <Card
            className="h-full rounded-2xl border-border bg-card/60 p-8 transition-shadow hover:shadow-lg"
            aria-labelledby="compliance-soc2"
          >
            <IconCardHeader icon={Shield} title="SOC2" subtitle="US Standard" titleId="compliance-soc2" />
            <CardContent className="p-0">
              <ul className="space-y-3">
                <BulletListItem variant="check" title="Auditor query API" />
                <BulletListItem variant="check" title="32 audit event types" />
                <BulletListItem variant="check" title="7-year retention (Type II)" />
                <BulletListItem variant="check" title="Tamper-evident hash chains" />
                <BulletListItem variant="check" title="Access control logging" />
                <BulletListItem variant="check" title="Encryption at rest" />
              </ul>
              <div className="mt-6">
                <div className="rounded-lg border border-chart-3/50 bg-chart-3/10 p-4">
                  <div className="mb-2 font-semibold text-chart-3">Trust Service Criteria</div>
                  <div className="space-y-1 text-xs text-foreground/85">
                    <div>✓ Security (CC1-CC9)</div>
                    <div>✓ Availability (A1.1-A1.3)</div>
                    <div>✓ Confidentiality (C1.1-C1.2)</div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* ISO 27001 Pillar */}
          <Card
            className="h-full rounded-2xl border-border bg-card/60 p-8 transition-shadow hover:shadow-lg"
            aria-labelledby="compliance-iso27001"
          >
            <IconCardHeader
              icon={Lock}
              title="ISO 27001"
              subtitle="International Standard"
              titleId="compliance-iso27001"
            />
            <CardContent className="p-0">
              <ul className="space-y-3">
                <BulletListItem variant="check" title="Incident records (A.16)" />
                <BulletListItem variant="check" title="3-year minimum retention" />
                <BulletListItem variant="check" title="Access logging (A.9)" />
                <BulletListItem variant="check" title="Crypto controls (A.10)" />
                <BulletListItem variant="check" title="Ops security (A.12)" />
                <BulletListItem variant="check" title="Security policies (A.5)" />
              </ul>
              <div className="mt-6">
                <div className="rounded-lg border border-chart-3/50 bg-chart-3/10 p-4">
                  <div className="mb-2 font-semibold text-chart-3">ISMS Controls</div>
                  <div className="space-y-1 text-xs text-foreground/85">
                    <div>✓ 114 controls implemented</div>
                    <div>✓ Risk assessment framework</div>
                    <div>✓ Continuous monitoring</div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Audit Readiness Band */}
        <div className="animate-in fade-in-50 rounded-2xl border border-primary/20 bg-primary/5 p-8 text-center [animation-delay:200ms]">
          <h3 className="mb-2 text-2xl font-semibold text-foreground">Ready for Your Compliance Audit</h3>
          <p className="mb-2 text-foreground/85">
            Download our compliance documentation package or schedule a call with our compliance team.
          </p>
          <p
            id="compliance-pack-note"
            className="mb-6 text-sm text-muted-foreground"
            aria-label="Compliance pack includes endpoints, retention policy, and audit-logging design"
          >
            Pack includes endpoints, retention policy, and audit-logging design.
          </p>
          <div className="flex flex-col items-center justify-center gap-3 sm:flex-row">
            <Button
              size="lg"
              asChild
              aria-describedby="compliance-pack-note"
              className="transition-transform active:scale-[0.98]"
            >
              <Link href="/compliance/download">Download Compliance Pack</Link>
            </Button>
            <Button
              size="lg"
              variant="outline"
              asChild
              aria-describedby="compliance-pack-note"
              className="transition-transform active:scale-[0.98]"
            >
              <Link href="/contact/compliance">Talk to Compliance Team</Link>
            </Button>
          </div>
          <p className="mt-6 text-xs text-muted-foreground">rbee (pronounced "are-bee")</p>
        </div>
      </div>
    </section>
  )
}

// frontend/bin/commercial/app/stories/organisms/EnterpriseCompliance/EnterpriseCompliance.vue
<!-- Created by: TEAM-FE-000 (Scaffolding) -->
<!-- TEAM-FE-008: Implemented EnterpriseCompliance -->
<script setup lang="ts">
import { Button } from '~/stories'
import { FileCheck, Shield, Lock, Globe } from 'lucide-vue-next'

interface ComplianceStandard {
  icon: any
  title: string
  subtitle: string
  items: string[]
  endpoints?: string[]
  criteria?: string[]
}

interface Props {
  title?: string
  subtitle?: string
  standards?: ComplianceStandard[]
  ctaTitle?: string
  ctaSubtitle?: string
  primaryCta?: string
  secondaryCta?: string
}

withDefaults(defineProps<Props>(), {
  title: 'Compliance by Design',
  subtitle:
    'rbee is built from the ground up to meet GDPR, SOC2, and ISO 27001 requirements. Not bolted on as an afterthought.',
  standards: () => [
    {
      icon: Globe,
      title: 'GDPR',
      subtitle: 'EU Regulation',
      items: [
        '7-year audit retention (Article 30)',
        'Data access records (Article 15)',
        'Right to erasure tracking (Article 17)',
        'Consent management (Article 7)',
        'Data residency controls (Article 44)',
        'Breach notification (Article 33)',
      ],
      endpoints: [
        'GET /v2/compliance/data-access',
        'POST /v2/compliance/data-export',
        'POST /v2/compliance/data-deletion',
        'GET /v2/compliance/audit-trail',
      ],
    },
    {
      icon: Shield,
      title: 'SOC2',
      subtitle: 'US Standard',
      items: [
        'Auditor access (query API)',
        'Security event logging (32 types)',
        '7-year retention (Type II)',
        'Tamper-evident storage (hash chains)',
        'Access control logging',
        'Encryption at rest',
      ],
      criteria: ['✓ Security (CC1-CC9)', '✓ Availability (A1.1-A1.3)', '✓ Confidentiality (C1.1-C1.2)'],
    },
    {
      icon: Lock,
      title: 'ISO 27001',
      subtitle: 'International',
      items: [
        'Security incident records (A.16)',
        '3-year retention (minimum)',
        'Access control logging (A.9)',
        'Cryptographic controls (A.10)',
        'Operations security (A.12)',
        'Information security policies (A.5)',
      ],
      criteria: ['✓ 114 controls implemented', '✓ Risk assessment framework', '✓ Continuous monitoring'],
    },
  ],
  ctaTitle: 'Ready for Your Compliance Audit',
  ctaSubtitle: 'Download our compliance documentation package or schedule a call with our compliance team.',
  primaryCta: 'Download Compliance Pack',
  secondaryCta: 'Talk to Compliance Team',
})
</script>

<template>
  <section id="compliance" class="border-b border-border bg-background px-6 py-24">
    <div class="mx-auto max-w-7xl">
      <div class="mb-16 text-center">
        <h2 class="mb-4 text-4xl font-bold text-foreground">{{ title }}</h2>
        <p class="mx-auto max-w-3xl text-balance text-xl text-muted-foreground">
          {{ subtitle }}
        </p>
      </div>

      <div class="grid gap-8 lg:grid-cols-3">
        <div v-for="(standard, i) in standards" :key="i" class="rounded-lg border border-border bg-card p-8">
          <div class="mb-6 flex items-center gap-3">
            <div class="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10">
              <component :is="standard.icon" class="h-6 w-6 text-primary" />
            </div>
            <div>
              <h3 class="text-2xl font-bold text-foreground">{{ standard.title }}</h3>
              <p class="text-sm text-muted-foreground">{{ standard.subtitle }}</p>
            </div>
          </div>

          <div class="space-y-3">
            <div v-for="(item, j) in standard.items" :key="j" class="flex items-start gap-2">
              <FileCheck class="mt-0.5 h-4 w-4 shrink-0 text-accent" />
              <span class="text-sm leading-relaxed text-muted-foreground">{{ item }}</span>
            </div>
          </div>

          <div v-if="standard.endpoints" class="mt-6 rounded-lg border border-accent/30 bg-accent/10 p-4">
            <div class="mb-1 font-semibold text-accent-foreground">Compliance Endpoints</div>
            <div class="space-y-1 text-xs text-muted-foreground">
              <div v-for="(endpoint, j) in standard.endpoints" :key="j">{{ endpoint }}</div>
            </div>
          </div>

          <div v-if="standard.criteria" class="mt-6 rounded-lg border border-accent/30 bg-accent/10 p-4">
            <div class="mb-1 font-semibold text-accent-foreground">{{ standard.title === 'SOC2' ? 'Trust Service Criteria' : 'ISMS Controls' }}</div>
            <div class="space-y-1 text-xs text-muted-foreground">
              <div v-for="(criterion, j) in standard.criteria" :key="j">{{ criterion }}</div>
            </div>
          </div>
        </div>
      </div>

      <!-- Bottom CTA -->
      <div class="mt-12 rounded-lg border border-primary/20 bg-primary/5 p-8 text-center">
        <h3 class="mb-2 text-2xl font-semibold text-foreground">{{ ctaTitle }}</h3>
        <p class="mb-6 text-muted-foreground">
          {{ ctaSubtitle }}
        </p>
        <div class="flex flex-wrap justify-center gap-4">
          <Button size="lg" class="bg-primary text-primary-foreground hover:bg-primary/90">
            {{ primaryCta }}
          </Button>
          <Button size="lg" variant="outline" class="border-border text-foreground hover:bg-secondary">
            {{ secondaryCta }}
          </Button>
        </div>
      </div>
    </div>
  </section>
</template>
