// frontend/libs/storybook/stories/organisms/EnterpriseComparison/EnterpriseComparison.vue
<!-- Created by: TEAM-FE-000 (Scaffolding) -->
<!-- TEAM-FE-008: Implemented EnterpriseComparison -->
<script setup lang="ts">
import { Check, X } from 'lucide-vue-next'

interface ComparisonRow {
  feature: string
  rbee: boolean | string
  openai: boolean | string
  azure: boolean | string
}

interface Props {
  title?: string
  subtitle?: string
  comparisonData?: ComparisonRow[]
  disclaimer?: string
}

withDefaults(defineProps<Props>(), {
  title: 'Why Enterprises Choose rbee',
  subtitle: "Compare rbee's compliance and security features against external AI providers.",
  comparisonData: () => [
    { feature: 'Data Sovereignty', rbee: true, openai: false, azure: 'Partial' },
    { feature: 'EU-Only Deployment', rbee: true, openai: false, azure: 'Partial' },
    { feature: 'GDPR Compliant', rbee: true, openai: 'Partial', azure: 'Partial' },
    { feature: 'Immutable Audit Logs', rbee: true, openai: false, azure: false },
    { feature: '7-Year Audit Retention', rbee: true, openai: false, azure: false },
    { feature: 'SOC2 Type II Ready', rbee: true, openai: true, azure: true },
    { feature: 'ISO 27001 Aligned', rbee: true, openai: true, azure: true },
    { feature: 'Zero US Cloud Dependencies', rbee: true, openai: false, azure: false },
    { feature: 'On-Premises Deployment', rbee: true, openai: false, azure: false },
    { feature: 'Complete Control', rbee: true, openai: false, azure: 'Partial' },
    { feature: 'Custom SLAs', rbee: true, openai: false, azure: true },
    { feature: 'White-Label Option', rbee: true, openai: false, azure: false },
  ],
  disclaimer: '* Comparison based on publicly available information as of October 2025',
})

const renderCell = (value: boolean | string) => {
  if (value === true) return { type: 'check', class: 'text-accent' }
  if (value === false) return { type: 'x', class: 'text-destructive' }
  return { type: 'text', text: value, class: 'text-muted-foreground' }
}
</script>

<template>
  <section class="border-b border-border bg-background px-6 py-24">
    <div class="mx-auto max-w-7xl">
      <div class="mb-16 text-center">
        <h2 class="mb-4 text-4xl font-bold text-foreground">{{ title }}</h2>
        <p class="mx-auto max-w-3xl text-balance text-xl text-muted-foreground">
          {{ subtitle }}
        </p>
      </div>

      <div class="overflow-x-auto">
        <table class="w-full border-collapse">
          <thead>
            <tr class="border-b border-border">
              <th class="p-4 text-left text-sm font-semibold text-muted-foreground">Feature</th>
              <th class="bg-primary/5 p-4 text-center text-sm font-semibold text-primary">
                rbee (Self-Hosted)
              </th>
              <th class="p-4 text-center text-sm font-semibold text-muted-foreground">OpenAI / Anthropic</th>
              <th class="p-4 text-center text-sm font-semibold text-muted-foreground">Azure OpenAI</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(row, i) in comparisonData" :key="i" class="border-b border-border">
              <td class="p-4 text-sm text-muted-foreground">{{ row.feature }}</td>
              <td class="bg-primary/5 p-4 text-center">
                <Check v-if="renderCell(row.rbee).type === 'check'" class="mx-auto h-5 w-5" :class="renderCell(row.rbee).class" />
                <X v-else-if="renderCell(row.rbee).type === 'x'" class="mx-auto h-5 w-5" :class="renderCell(row.rbee).class" />
                <span v-else class="text-sm" :class="renderCell(row.rbee).class">{{ renderCell(row.rbee).text }}</span>
              </td>
              <td class="p-4 text-center">
                <Check v-if="renderCell(row.openai).type === 'check'" class="mx-auto h-5 w-5" :class="renderCell(row.openai).class" />
                <X v-else-if="renderCell(row.openai).type === 'x'" class="mx-auto h-5 w-5" :class="renderCell(row.openai).class" />
                <span v-else class="text-sm" :class="renderCell(row.openai).class">{{ renderCell(row.openai).text }}</span>
              </td>
              <td class="p-4 text-center">
                <Check v-if="renderCell(row.azure).type === 'check'" class="mx-auto h-5 w-5" :class="renderCell(row.azure).class" />
                <X v-else-if="renderCell(row.azure).type === 'x'" class="mx-auto h-5 w-5" :class="renderCell(row.azure).class" />
                <span v-else class="text-sm" :class="renderCell(row.azure).class">{{ renderCell(row.azure).text }}</span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="mt-8 text-center text-sm text-muted-foreground">
        {{ disclaimer }}
      </div>
    </div>
  </section>
</template>

// frontend/packages/rbee-ui/src/organisms/Enterprise/EnterpriseComparison/EnterpriseComparison.tsx
'use client'

import { cn } from '@rbee/ui/utils'
import { useState } from 'react'
import { Legend } from '../../../atoms/Legend'
import { MatrixCard } from '@rbee/ui/molecules'
import { MatrixTable } from '@rbee/ui/molecules'
import { FEATURES, PROVIDERS } from '../ComparisonData/comparison-data'

export function EnterpriseComparison() {
	const [selectedProvider, setSelectedProvider] = useState(0)

	return (
		<section aria-labelledby="comparison-h2" className="border-b border-border bg-background px-6 py-24">
			<div className="mx-auto max-w-7xl">
				{/* Header Block */}
				<div className="mb-12 text-center animate-in fade-in-50 slide-in-from-bottom-2">
					<p className="mb-2 text-sm font-semibold uppercase tracking-wide text-primary">Feature Matrix</p>
					<h2 id="comparison-h2" className="mb-4 text-4xl font-bold text-foreground">
						Why Enterprises Choose rbee
					</h2>
					<p className="mx-auto max-w-3xl text-balance text-xl text-muted-foreground">
						See how rbee's compliance and security compare to external AI providers.
					</p>
					<p className="mt-3 text-xs text-muted-foreground/70">
						Based on public materials; verify requirements with your legal team.
					</p>
				</div>

				{/* Legend */}
				<Legend className="mb-8 animate-in fade-in-50" style={{ animationDelay: '100ms' }} />

				{/* Desktop Table (md+) */}
				<div className="hidden md:block animate-in fade-in-50" style={{ animationDelay: '150ms' }}>
					<MatrixTable columns={PROVIDERS} rows={FEATURES} />
				</div>

				{/* Mobile Cards (<md) */}
				<div className="md:hidden animate-in fade-in-50" style={{ animationDelay: '150ms' }}>
					{/* Provider Switcher */}
					<div className="mb-6 flex items-center justify-center gap-2 rounded-lg border bg-card/60 p-1">
						{PROVIDERS.map((provider, index) => (
							<button
								key={provider.key}
								onClick={() => setSelectedProvider(index)}
								className={cn(
									'flex-1 rounded-md px-3 py-2 text-xs font-medium transition-colors',
									selectedProvider === index
										? 'bg-primary text-primary-foreground'
										: 'text-muted-foreground hover:text-foreground',
								)}
								aria-pressed={selectedProvider === index}
							>
								{provider.label}
							</button>
						))}
					</div>

					{/* Single Card for Selected Provider */}
					<MatrixCard provider={PROVIDERS[selectedProvider]} rows={FEATURES} />

					{/* Jump to Desktop Link (for screen readers) */}
					<a
						href="#comparison-h2"
						className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 focus:rounded focus:bg-primary focus:px-4 focus:py-2 focus:text-primary-foreground"
					>
						Jump to desktop table
					</a>
				</div>

				{/* Footnote */}
				<div className="mt-8 text-center text-sm text-muted-foreground">
					* Comparison based on publicly available information as of October 2025.
				</div>
			</div>
		</section>
	)
}
