// frontend/bin/commercial/app/stories/organisms/EmailCapture/EmailCapture.vue
<!-- Created by: TEAM-FE-000 (Scaffolding) -->
<!-- TEAM-FE-CONSOLIDATE: Implemented EmailCapture with design tokens -->
<script setup lang="ts">
import { ref } from 'vue'
import { Button, Input } from '~/stories'
import { Mail, CheckCircle2, Github } from 'lucide-vue-next'

interface Props {
  title?: string
  description?: string
  statusBadge?: string
  privacyText?: string
  githubText?: string
  githubUrl?: string
}

const props = withDefaults(defineProps<Props>(), {
  title: 'Be the First to Know',
  description: 'rbee is actively being built. Join our waitlist to get early access, updates on development progress, and exclusive launch benefits.',
  statusBadge: 'Currently in Development (M0 - 68% Complete)',
  privacyText: 'No spam. Unsubscribe anytime. We respect your privacy.',
  githubText: 'Star us on GitHub',
  githubUrl: 'https://github.com/veighnsche/llama-orch',
})

const email = ref('')
const submitted = ref(false)

const handleSubmit = (e: Event) => {
  e.preventDefault()
  // TODO: Wire up to actual email service (backend integration)
  console.log('Email submitted:', email.value)
  submitted.value = true
  setTimeout(() => {
    submitted.value = false
    email.value = ''
  }, 3000)
}
</script>

<template>
  <section class="py-24 bg-gradient-to-br from-background via-secondary to-background">
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
      <div class="inline-flex items-center gap-2 px-4 py-2 bg-primary/10 border border-primary/20 rounded-full text-primary text-sm font-medium mb-6">
        <span class="relative flex h-2 w-2">
          <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary opacity-75"></span>
          <span class="relative inline-flex rounded-full h-2 w-2 bg-primary"></span>
        </span>
        {{ statusBadge }}
      </div>

      <h2 class="text-4xl md:text-5xl font-bold text-foreground mb-6">{{ title }}</h2>

      <p class="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto leading-relaxed">
        {{ description }}
      </p>

      <form v-if="!submitted" @submit="handleSubmit" class="flex flex-col sm:flex-row gap-4 max-w-md mx-auto">
        <div class="flex-1 relative">
          <Mail class="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
          <Input
            v-model="email"
            type="email"
            placeholder="your@email.com"
            required
            class="pl-10 h-12"
          />
        </div>
        <Button
          type="submit"
          size="lg"
          variant="default"
          class="h-12 px-8"
        >
          Join Waitlist
        </Button>
      </form>

      <div v-else class="flex items-center justify-center gap-2 text-primary text-lg">
        <CheckCircle2 :size="24" />
        <span>Thanks! We'll keep you updated.</span>
      </div>

      <p class="text-sm text-muted-foreground mt-6">{{ privacyText }}</p>

      <div class="mt-12 pt-12 border-t border-border">
        <p class="text-muted-foreground mb-4">Want to contribute or follow development?</p>
        <a
          :href="githubUrl"
          target="_blank"
          rel="noopener noreferrer"
          class="inline-flex items-center gap-2 text-primary hover:text-primary/80 transition-colors font-medium"
        >
          <Github :size="20" />
          {{ githubText }}
        </a>
      </div>
    </div>
  </section>
</template>

// frontend/bin/commercial/components/email-capture.tsx
"use client"

import type React from "react"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Mail, CheckCircle2 } from "lucide-react"

export function EmailCapture() {
  const [email, setEmail] = useState("")
  const [submitted, setSubmitted] = useState(false)

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    // TODO: Wire up to actual email service
    console.log("Email submitted:", email)
    setSubmitted(true)
    setTimeout(() => {
      setSubmitted(false)
      setEmail("")
    }, 3000)
  }

  return (
    <section className="py-24 bg-background">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
        <div className="inline-flex items-center gap-2 px-4 py-2 bg-primary/10 border border-primary/20 rounded-full text-primary text-sm font-medium mb-6">
          <span className="relative flex h-2 w-2">
            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary opacity-75"></span>
            <span className="relative inline-flex rounded-full h-2 w-2 bg-primary"></span>
          </span>
          Currently in Development (M0 - 68% Complete)
        </div>

        <h2 className="text-4xl md:text-5xl font-bold text-foreground mb-6">Be the First to Know</h2>

        <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto leading-relaxed">
          rbee is actively being built. Join our waitlist to get early access, updates on development progress, and
          exclusive launch benefits.
        </p>

        {!submitted ? (
          <form onSubmit={handleSubmit} className="flex flex-col sm:flex-row gap-4 max-w-md mx-auto">
            <div className="flex-1 relative">
              <Mail className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
              <Input
                type="email"
                placeholder="your@email.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
                className="pl-10 bg-card border-border text-foreground placeholder:text-muted-foreground h-12"
              />
            </div>
            <Button
              type="submit"
              size="lg"
              className="bg-primary hover:bg-primary/90 text-primary-foreground font-semibold h-12 px-8"
            >
              Join Waitlist
            </Button>
          </form>
        ) : (
          <div className="flex items-center justify-center gap-2 text-chart-3 text-lg">
            <CheckCircle2 className="w-6 h-6" />
            <span>Thanks! We'll keep you updated.</span>
          </div>
        )}

        <p className="text-sm text-muted-foreground mt-6">No spam. Unsubscribe anytime. We respect your privacy.</p>

        <div className="mt-12 pt-12 border-t border-border">
          <p className="text-muted-foreground mb-4">Want to contribute or follow development?</p>
          <a
            href="https://github.com/veighnsche/llama-orch"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 text-primary hover:text-primary/90 transition-colors font-medium"
          >
            <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <path
                fillRule="evenodd"
                d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
                clipRule="evenodd"
              />
            </svg>
            Star us on GitHub
          </a>
        </div>
      </div>
    </section>
  )
}
