// frontend/libs/rbee-ui/src/atoms/Button.tsx
import * as React from 'react';
import { cn } from '../utils';

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'default' | 'secondary' | 'outline' | 'ghost' | 'destructive';
  size?: 'sm' | 'md' | 'lg' | 'icon';
  asChild?: boolean;
}

/**
 * Button component - Primary interactive element
 * 
 * @example
 * ```tsx
 * <Button variant="default" size="md">Click me</Button>
 * <Button variant="outline">Secondary action</Button>
 * ```
 */
export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant = 'default', size = 'md', ...props }, ref) => {
    return (
      <button
        ref={ref}
        className={cn(
          // Base styles
          'inline-flex items-center justify-center gap-2 rounded-lg font-medium',
          'transition-colors focus-visible:outline-none focus-visible:ring-2',
          'focus-visible:ring-[var(--rbee-ring)] focus-visible:ring-offset-2',
          'disabled:pointer-events-none disabled:opacity-50',
          
          // Variants
          {
            'bg-[var(--rbee-primary)] text-[var(--rbee-primary-foreground)] hover:opacity-90':
              variant === 'default',
            'bg-[var(--rbee-secondary)] text-[var(--rbee-secondary-foreground)] hover:bg-[var(--rbee-secondary)]/80':
              variant === 'secondary',
            'border border-[var(--rbee-border)] bg-transparent hover:bg-[var(--rbee-accent)] hover:text-[var(--rbee-accent-foreground)]':
              variant === 'outline',
            'hover:bg-[var(--rbee-accent)] hover:text-[var(--rbee-accent-foreground)]':
              variant === 'ghost',
            'bg-[var(--rbee-destructive)] text-[var(--rbee-destructive-foreground)] hover:opacity-90':
              variant === 'destructive',
          },
          
          // Sizes
          {
            'h-9 px-3 text-sm': size === 'sm',
            'h-10 px-4 text-base': size === 'md',
            'h-11 px-6 text-lg': size === 'lg',
            'h-10 w-10 p-0': size === 'icon',
          },
          
          className
        )}
        {...props}
      />
    );
  }
);

Button.displayName = 'Button';

// frontend/bin/commercial/app/stories/atoms/Button/Button.vue
<!-- Created by: TEAM-FE-001 -->
<!-- TEAM-FE-001: Updated to use Radix Vue Slot for asChild pattern -->
<!-- TEAM-FE-011: Added cursor-pointer to base button styles -->
<script setup lang="ts">
import { computed } from 'vue'
import { cva, type VariantProps } from 'class-variance-authority'
import { Slot } from 'radix-vue'
import { cn } from '../../../lib/utils'

// Define variants using CVA - ported from React reference
const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 cursor-pointer [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4 shrink-0 [&_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
  {
    variants: {
      variant: {
        default: 'bg-primary text-primary-foreground hover:bg-primary/90',
        destructive:
          'bg-destructive text-white hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60',
        outline:
          'border bg-background shadow-xs hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50',
        secondary:
          'bg-secondary text-secondary-foreground hover:bg-secondary/80',
        ghost:
          'hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50',
        link: 'text-primary underline-offset-4 hover:underline',
      },
      size: {
        default: 'h-9 px-4 py-2 has-[>svg]:px-3',
        sm: 'h-8 rounded-md gap-1.5 px-3 has-[>svg]:px-2.5',
        lg: 'h-10 rounded-md px-6 has-[>svg]:px-4',
        icon: 'size-9',
        'icon-sm': 'size-8',
        'icon-lg': 'size-10',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'default',
    },
  }
)

// Define props interface
interface Props {
  variant?: VariantProps<typeof buttonVariants>['variant']
  size?: VariantProps<typeof buttonVariants>['size']
  disabled?: boolean
  type?: 'button' | 'submit' | 'reset'
  asChild?: boolean
  class?: string
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'default',
  size: 'default',
  disabled: false,
  type: 'button',
  asChild: false,
})

// Compute classes
const classes = computed(() =>
  cn(buttonVariants({ variant: props.variant, size: props.size }), props.class)
)
</script>

<template>
  <Slot
    v-if="asChild"
    :class="classes"
    data-slot="button"
  >
    <slot />
  </Slot>
  <button
    v-else
    :type="type"
    :disabled="disabled"
    :class="classes"
    data-slot="button"
  >
    <slot />
  </button>
</template>
