// frontend/bin/commercial/components/atoms/Button/Button.tsx
import * as React from 'react'
import { Slot } from '@radix-ui/react-slot'
import { cva, type VariantProps } from 'class-variance-authority'

import { cn } from '@/lib/utils'

const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4 shrink-0 [&_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-1 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
  {
    variants: {
      variant: {
        default: 'bg-primary text-primary-foreground hover:bg-primary/90',
        destructive:
          'bg-destructive text-destructive-foreground hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60',
        outline:
          'border bg-background shadow-xs hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50',
        secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
        ghost: 'hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50',
        link: 'text-primary underline-offset-4 hover:underline',
      },
      size: {
        default: 'h-9 px-4 py-2 has-[>svg]:px-3',
        sm: 'h-8 rounded-md gap-1.5 px-3 has-[>svg]:px-2.5',
        lg: 'h-10 rounded-md px-6 has-[>svg]:px-4',
        icon: 'size-9',
        'icon-sm': 'size-8',
        'icon-lg': 'size-10',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'default',
    },
  },
)

function Button({
  className,
  variant,
  size,
  asChild = false,
  ...props
}: React.ComponentProps<'button'> &
  VariantProps<typeof buttonVariants> & {
    asChild?: boolean
  }) {
  const Comp = asChild ? Slot : 'button'

  return <Comp data-slot="button" className={cn(buttonVariants({ variant, size, className }))} {...props} />
}

export { Button, buttonVariants }

// consumers/.business/commercial-frontend/src/components/ui/Button.vue
<script setup lang="ts">
import { computed } from 'vue'
import { RouterLink, type RouteLocationRaw } from 'vue-router'

const props = withDefaults(defineProps<{
  as?: 'button' | 'a' | 'router-link'
  to?: RouteLocationRaw
  href?: string
  type?: 'button' | 'submit' | 'reset'
  variant?: 'primary' | 'ghost' | 'link'
  size?: 'sm' | 'md' | 'lg'
  iconOnly?: boolean
  disabled?: boolean
  block?: boolean
}>(), {
  as: undefined,
  type: 'button',
  variant: 'primary',
  size: 'md',
  iconOnly: false,
  disabled: false,
  block: false,
})

const isRouter = computed(() => props.as === 'router-link' || !!props.to)
const isAnchor = computed(() => props.as === 'a' || (!!props.href && !isRouter.value))

const tag = computed(() => (isRouter.value ? RouterLink : isAnchor.value ? 'a' : 'button'))

const attrs = computed(() => {
  const a: Record<string, unknown> = {}
  if (isRouter.value) a.to = props.to
  else if (isAnchor.value) a.href = props.href
  else {
    a.type = props.type
    a.disabled = props.disabled
  }
  return a
})

const classes = computed(() => {
  const variantClass = props.variant === 'primary'
    ? 'ui-btn--primary'
    : props.variant === 'ghost'
    ? 'ui-btn--ghost'
    : 'ui-btn--link'

  return [
    'ui-btn',
    variantClass,
    `ui-btn--${props.size}`,
    props.iconOnly ? 'ui-btn--icon' : null,
    props.block ? 'ui-btn--block' : null,
  ]
})
</script>

<template>
  <component :is="tag" v-bind="attrs" :class="classes">
    <slot />
  </component>
</template>

<style scoped>
.ui-btn {
  -webkit-tap-highlight-color: transparent;
  appearance: none;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: .4rem;
  border-radius: var(--radius-md);
  border: 1px solid var(--surface-muted);
  background: var(--surface-alt);
  color: var(--text);
  font-weight: 700;
  text-decoration: none;
  cursor: pointer;
  transition: transform .06s ease, box-shadow .06s ease, border-color .2s ease, background .2s ease, filter .2s ease;
}
.ui-btn:hover { transform: translateY(-1px); }
.ui-btn:focus-visible { outline: 2px solid var(--ring); outline-offset: 2px; }
.ui-btn:disabled { opacity: .6; cursor: not-allowed; transform: none; }

/* variants */
.ui-btn--primary {
  background: var(--acc-cyan);
  border-color: var(--acc-cyan);
  color: var(--surface-alt);
}
.ui-btn--primary:hover { filter: brightness(1.05); }

.ui-btn--ghost {
  background: var(--surface-alt);
  border-color: var(--surface-muted);
  color: var(--text);
}

.ui-btn--link {
  background: transparent;
  border-color: transparent;
  color: var(--acc-purple);
}
.ui-btn--link:hover {
  text-decoration: underline;
  transform: none;
}

/* layout helpers */
.ui-btn--block { width: 100%; display: inline-flex; }

/* sizes */
.ui-btn--sm { padding: .35rem .6rem; font-size: .9rem; }
.ui-btn--md { padding: .55rem .8rem; font-size: 1rem; }
.ui-btn--lg { padding: .7rem 1rem; font-size: 1.05rem; }

/* icon-only adjustments */
.ui-btn--icon { gap: 0; padding: 0; width: 38px; height: 38px; }
.ui-btn--icon.ui-btn--sm { width: 32px; height: 32px; }
.ui-btn--icon.ui-btn--md { width: 38px; height: 38px; }
.ui-btn--icon.ui-btn--lg { width: 44px; height: 44px; }

@media (prefers-color-scheme: dark) {
  .ui-btn--ghost {
    background: var(--surface);
    border-color: var(--surface-muted);
    color: var(--text);
  }
  .ui-btn--link { color: var(--acc-cyan); }
}
</style>
